Alloy/commands/compile/styler.js
test/apps/testing/ALOY-1219/alloy.js
test/apps/testing/ALOY-1219/config.json
test/apps/testing/ALOY-1219/controllers/index.js
test/apps/testing/ALOY-1219/styles/app.tss
test/apps/testing/ALOY-1219/styles/index.tss
test/apps/testing/ALOY-1219/views/index.xml

Alloy is currently catching and interpreting `{{ }}` as an alloy binding when it should only catch `{ }`.
This change is needed for https://github.com/dbankier/nano.

regex change to support {{ }}

---

test/apps/ui/android_menu/alloy.js
test/apps/ui/android_menu/views/android/index.xml

- Updates comments to better reflect how Menu/MenuItem works by default with TI SDK 3.3.0 and later, as action bar items, not the options menu of yore).
- Conditionally displays the "Press the Menu button" label only if the API level is 10 or earlier (pre-Honeycomb).

[ALOY-1198] Update ui/android_menu text for Honeycomb/action bar usage

---

Alloy/lib/alloy/controllers/BaseController.js
docs/apidoc/collection.js
docs/apidoc/controller.js

https://jira.appcelerator.org/browse/TIDOC-2002
Note: To get the code samples to display properly (with proper indentation), they needed to have a single tab indent from the edge of the document. So they don't align with the rest of the code/docs. :crying_cat_face: 
Also added some links in collection.js.

Added examples to docs for public Alloy.Controller/Alloy.Controller.UI APIs

---

Alloy/builtins/animation.js
Alloy/builtins/dialogs.js
Alloy/builtins/measurement.js
Alloy/builtins/sha1.js
Alloy/builtins/social.js
Alloy/builtins/string.js
Alloy/lib/alloy.js
Alloy/lib/alloy/controllers/BaseController.js
docs/apidoc/backbone.js
docs/apidoc/builtins.js
docs/apidoc/collection.js
docs/apidoc/controller.js
docs/apidoc/model.js
docs/apidoc/moment.js
docs/apidoc/widgets.js

To support https://jira.appcelerator.org/browse/TIDOC-2058.
Note: This step is done automatically for the Titanium docs, since they need to converted from YAML to JSDuck format anyway. Alloy docs are in JSDuck format already, so they are passed as-is to JSDuck for processing. As there are only a few Alloy doc sources, it made sense just to add them manually.

[TIDOC-2058] Added @editurl JSDuck field that contains GitHub edit link for that class/API

---

Alloy/builtins/animation.js
Alloy/builtins/dialogs.js
Alloy/builtins/measurement.js
Alloy/builtins/sha1.js
Alloy/builtins/social.js
Alloy/builtins/string.js
Alloy/lib/alloy.js
Alloy/lib/alloy/controllers/BaseController.js
docs/apidoc/builtins.js
docs/apidoc/collection.js
docs/apidoc/controller.js
docs/apidoc/model.js
docs/apidoc/moment.js
docs/apidoc/widgets.js

I’ve found a better way to make it work on the doctools side, so no need to muck with the Alloy source.
This reverts commit ec0542368652e8c92f9d746940aa43f13da38633.

Revert "Added @editurl JSDuck field"

---

Alloy/commands/compile/index.js

add restrictionPath  when call parseAlloyComponent for controller that has no correcpoding view markup
This is a related with appcelerator/alloy#625 ( @xavierlacot )

fix restrictionPath missing

---

Alloy/common/constants.js

JIRA: https://jira.appcelerator.org/browse/ALOY-1257
Has been moved since 3.0.0: http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.iPad.DocumentViewer

[ALOY-1267] Map DocumentViewer to Ti.UI.iOS

---

Alloy/lib/alloy.js

This PR relates to ALOY-1276. Basically, it fixes a bug introduced in 84c9470d9932a5ad762f8220db79802d91ec4c86 which makes Alloy's `deepExtend()` method useless.
It might be a good idea to simple revert commit 84c9470d9932a5ad762f8220db79802d91ec4c86, but it would involve digging into the bug ALOY-1153 in a closer way.

[ALOY-1276] fixes deepExtend()

---

Alloy/commands/compile/styler.js

This bug is described in [[AC-189]](https://jira.appcelerator.org/browse/AC-189).
In some cases, when the developer overloads in a given stylesheet some styles defined in the `app.tss` global style file, the alloy compilation won't produce the same resulting javascript accross successive compilations.
Alloy's styler orders style rules to define their priority, but there's a bug with the `app.tss` global styles being cached and therefore not correctly being counted by the styler when they're loaded back from cache, during a latter compilation phase when `app.tss` didn't change.
This fix simply correctly increments the styleCounter with the number of rules loaded from the global style cache. Kudos to my colleague @vdesdoigts for spotting the bug and isolating a reproducible symptom.

Fixed a style ordering bug

---

Alloy/template/app.tss

Windows also defaults to white labels, so since we set the Ti.UI.Window backgrounds to white, the label should be black or it will be invisible.
https://jira.appcelerator.org/browse/ALOY-1288

[ALOY-1288] Windows: Label not visible when using default app.tss

---

hooks/alloy.js
package.json

https://jira.appcelerator.org/browse/CLI-768
Dependent: https://github.com/appcelerator/appc-cli-titanium/pull/126

[CLI-768] Alloy app fails to build on Windows with error "Alloy compiler failed"

---

hooks/deepclean.js
package.json

https://jira.appcelerator.org/browse/ALOY-1305

[ALOY-1305] deepclean.js syntax error: missing semicolon

---

Alloy/commands/extract-i18n/index.js
Alloy/commands/generate/index.js
Alloy/lib/alloy.js
Alloy/template/app.tss
CHANGELOG.md
README.md
docs/apidoc/widgets.js
hooks/README.md
jakelib/readme.md
package.json
samples/mapping/controllers/index.js

https://jira.appcelerator.org/browse/ALOY-1273

[ALOY-1273] Code documentation contains links to out-dated Titanium docs

---

Alloy/commands/compile/index.js

This PR fixes the JIRA ticket [AC-540](https://jira.appcelerator.org/browse/AC-540).
Since [this commit|https://github.com/feons/alloy/commit](25855c1f342eecf6cb6e69dca007d05ebde1771b#diff-ddbdb7300fa15590afdfee9246ac61fcR177), Alloy's selective compilation is broken since the `Resources`'s `alloy.js` file gets replaced each and every time the alloy compile command is called.
Instead, the fix should look if there's a file restriction, and not replace `alloy.js` if this restriction does not affect this file.
This is particularly problematic when using some compilation watcher (aka. tishadow + grunt-tishadow), which look for changes in the `Resources` folder to re-launch the app. With the current change, the app will be refreshed using a template-based `alloy.js` file (not a recompiled …

[AC-540] Disable alloy.js template remplacement when alloy selective compilation is used

---

Alloy/builtins/moment/lang/ar-sa.js

Hi,
Arabic Saudi Arabic is the common use from GCC countries, Yemen, Egypt and Sudan.
Also using Arabic number ١ ٢ ٣ ٤ ٥ ٦ ٧ ٨  ٩ instead of English

Adding MomentJS most common Arabic format

---

samples/todo/styles/add.tss

Add font color 'black' to #itemField. As of Ti SDK 4.0, you can't read what you are typing into the text field otherwise. Seems to be a problem with only Android.

Make input text for Add feature readable on Android

---

Alloy/commands/compile/index.js

When compiling only `app/alloy.js`, generating `Resources/alloy.js` from template is not required.
Because `Resource/alloy.js` is not user's code but builtin code. So when compiling specific controller and alloy.js only, Generate `Resource/alloy.js` should be skipped.
Current version of alloy(1.7.32) has a problem related with this issue.
Reproduce steps
1. delete all file of `Resources` folder.
1. run : `alloy compile -q ios --config file=app/alloy.js`
1. you can check compiling result on `Resource`
1. `Resources/iphone/alloy.js` is generated from template 
1. But `Resources/iphone/alloy.js` is not optimized. It has uncompiled CONSTANT such as `OS_MOBILEWEB`. it makses `undefined` error on runtime.

Generating `Resources/alloy.js` from template is not required when selective compile

---

Alloy/commands/compile/parsers/Alloy.Abstract.ButtonName.js

https://jira.appcelerator.org/browse/ALOY-1297

[ALOY-1297] Cannot use localized strings for AlertDialog ButtonNames in XML

---

Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/index.js

If you have an Alloy component that uses databinding and has conditional code defined in the xml, the destroy function is not taking into consideration the fact that the component may be undefined before calling the `off` function.

Added check for variable existence before calling off in destroy function

---

Alloy/commands/compile/styler.js

Note: tests were failing before any changes were made. I did not look at fixing those tests
Fixes
[WARN]  ing: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
[ERROR]
[DEBUG]     at Function.createFromInputFallback (/Users/cgedrim/.nvm/versions/node/v4.2.6/lib/node_modules/alloy/node_modules/moment/moment.js:746:36)
[DEBUG]     at configFromString (/Users/cgedrim/.nvm/versions/node/v4.2.6/lib/node_modules/alloy/node_modules/moment/moment.js:826:32)
[DEBUG]     at configFromInput (/Users/cgedrim/.nvm/versions/node/v4.2.6/lib/node_modules/alloy/node_modules/moment/moment.js:1353:13)
[DEBUG]     at prepareConfig …

Ensure style is a date before calling createDate

---

Alloy/lib/alloy/sync/sql.js
package.json

- Bind the ```ResultSet``` context to the ```field``` call to prevent an invalid pointer
```Javascript
var booksDB = Ti.Database.open('booksDB');
booksDB.execute('CREATE TABLE IF NOT EXISTS books(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, author TEXT)');
booksDB.execute('REPLACE INTO books (title,author) VALUES (?,?)', ('Great Expectations', 'Charles Dickens'));
var result = booksDB.execute('SELECT * FROM books'),
getField = result.field; // INVALID
// getField = result.field.bind(result); // VALID
Ti.API.info('=== RESULT ===');
Ti.API.info('fieldCount: ' + result.fieldCount);
for (var i = 0, j = result.fieldCount; i < j; i++) {
Ti.API.info(getField(i));
}
Ti.API.info('==============');
result.close();
booksDB.close();
```
[JIRA …

[TIMOB-20577] Fix getField context for Windows

---

hooks/deepclean.js

Related to [TIMOB-20085](https://jira.appcelerator.org/browse/TIMOB-20085) and https://github.com/appcelerator/titanium_mobile/pull/7628
[hooks/deepclean.js](https://github.com/appcelerator/alloy/blob/master/hooks/deepclean.js) prevents from running SDK-specific `ti clean` hook because `deepclean.js` doesn't properly call finish callback.

[TIMOB-20085] "ti clean" does not scan SDK hooks

---

Alloy/commands/compile/index.js
Alloy/utils.js

#625 is a PR to allow compile only one specific file.
This PR supports compiling several specific files.
example:
```shell
alloy compile --config platform=ios,file=app/controllers/index.js,file=app/controller/myCtrl.js
```

support multiple restrict files

---

Alloy/commands/compile/index.js

This PR make you can skip the file when doing an optimization manually.
There are no reason to optimize js files which doesn't depends on alloy.
If you want to skip, add `optimizingExeptions` to `config.json`:
- If `app/lib/q.js`, the path should be `q.js`(see below. After compiling, `app/lib/q.js` to `q.js`)
```javascript
{
//...
"optimizingExceptions": [
"moment2.11.1.js",
"q.js",
"underscore1.8.3.js",
"sf.js",
"nl.fokkezb.html2as.js"
],
//...
}
```

Add optimizingExeptions option to config.json

---

Alloy/template/gitignore.txt

JIRA-Ticket: https://jira.appcelerator.org/browse/AC-4875
```
ti create -t app -n test --id com.test.test -p all -u test.de -d .
cd test
alloy new
```
still had an old gitignore without the /platform and /i18n (like in https://github.com/appcelerator/alloy/blob/master/templates/default/.gitignore)

[AC-4875] Update gitignore

---

Alloy/lib/alloy/sync/sql.js

https://jira.appcelerator.org/browse/TC-5486
It will be nice if sql sync adapter will pass model config to migration functions. It will get access to model columns inside migration for example.
``` javascript
migration.up = function(migrator, config) {
migrator.createTable(config);
// other migration actions
};
```

[ALOY-1278] Pass model config to migration functions

---

Alloy/commands/compile/ast/controller.js

*JIRA* https://jira.appcelerator.org/browse/ALOY-1570
*Description*
This is a typo when I converted the code from Uglify to Babel. It used to look for `exports.baseController` and I fudged the translation to be `export.baseController`.

[ALOY-1570] Alloy: exports.baseController does not work since 1.10.0 (Regression)

---

Alloy/commands/compile/parsers/Ti.UI.Toolbar.js
Alloy/common/constants.js

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25003
**Description:**
Remove implicit iOS namespace for Toolbar.
Add Android alloy parser for Toolbar.
I believe this would keep the backward compatibility for iOS since the new code is used only when the Toolbar is used as a custom ActionBar (which we will alloy only for Android). If we can further guard for that we could add that as well.

Move Toolbar to Ti.UI.Toolbar namespace

---

platforms/windows/index.js

JIRA:  https://jira.appcelerator.org/browse/ALOY-1582
`Ti.Platform.osname` should report windowsstore when target is ws-local, and windowsphone when target is wp-emulator/wp-device

[ALOY-1582] Fix Ti.Platform.osname on Windows

---

Alloy/lib/alloy/sync/sql.js

- In the event `db.execute()` returns no results, fallback to obtain `columns`
- This PR replaces the solution here: https://github.com/appcelerator/titanium_mobile/pull/9527
- Android 8.0 / iOS 11
- Follow the test case [here](https://jira.appcelerator.org/browse/TIMOB-20222)
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25397)

[TIMOB-25397] Fallback if empty ResultSet is returned

---

Alloy/commands/compile/sourceMapper.js
package-lock.json
package.json

**JIRA**: https://jira.appcelerator.org/browse/TISTUD-8942
**Description**
This boiled down to "some breakpoints were never honored in alloy apps".
After a lot of digging to isolate where the root cause was, I was able to validate the the debugger/SDK seemed fine, as a built alloy app could be debugged not he generated sources just fine.
Classic apps were OK, so it had to be alloy-specific.
I then dug into alloy's source mapping, since it's really a two-pass operation. First, we generate an initial file and our own source map. Then we hand that off to babel and it's supposed to transform the file more and generate the final source mapping. Great, right? Except babel produces intermittently invalid source maps: babel/babel#6008
The workaround here is to avoid trying to feed source maps to …

[TISTUD-8942] Android Debugger: Some breakpoints not hit if "Resume" is done anytime during debug

---

Jenkinsfile

Jenkins job has been failing for a while as it cant find appc-cli-wrapper, based off other projects I believe this is now the job we should be triggering. It might make more sense to also move to buildNPMPackage from pipeline-library

Correct appc-cli job name

---

Alloy/template/component.js

**JIRA**: https://jira.appcelerator.org/browse/ALOY-1602
I don't understand why it is necessary to remove `$model`, `__parentSymbol` or `__itemTemplate` from the `arguments` variable.
This is causing issues when passing `$model` for example to a controller which is inheriting from another controller as per [Alloy Controller Inheritance documentation](http://docs.appcelerator.com/platform/latest/#!/guide/Alloy_Controllers-section-src-34636384_AlloyControllers-Inheritance).
If we delete it from there, only the parent will have `$model` properly set but the child controller won't as it's deleted from `arguments`.
Another option would be to run `__processArg()` before calling the parent controller but this would mean only the child controller has `$model` properly set, it will be `null` for …

[ALOY-1602] Avoid some global variables to be only available in parent controller.

---

Alloy/template/gitignore.txt
templates/default/.gitignore
templates/two_tabbed/.gitignore

**JIRA**: https://jira.appcelerator.org/browse/ALOY-1609
Every time the alloy version changes, the alloy.js plugin file inside the plugin folder changes too. This pollutes git and a default procedure is to remove the file from git alltogether.

[ALOY-1609] Add plugins/ti.alloy to gitignore

---

.eslintrc.js
Alloy/commands/compile/index.js

https://jira.appcelerator.org/browse/ALOY-1606
After source map generation, the controller source file got optimized, which invalidates the source map.

[ALOY-1606] Android: Debugger not hitting breakpoints on Windows

---

Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/parsers/Alloy.Abstract.ItemTemplate.js
package-lock.json
package.json

- Support defining Alloy widgets in ListView templates
```XML
<Alloy>
<Window class="container" backgroundColor="white">
<ListView id="listView" defaultItemTemplate="template">
<Templates>
<ItemTemplate name="template">
<Widget src="test.widget" bindId="testWidget" id="testWidget"/>
</ItemTemplate>
</Templates>
<ListSection headerTitle="WIDGETS">
<ListItem testWidget:backgroundColor="red" />
<ListItem testWidget:backgroundColor="blue" />
<ListItem testWidget:backgroundColor="orange" />
</ListSection>
</ListView>
</Window>
</Alloy>
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24817)

[TIMOB-24817] Support Widgets in ListView templates

---

Alloy/builtins/dialogs.js

I've added an optional failure callback on alloy/dialogs. This way if 'No' is chosen I can run a function.

added optional failure callback on alloy/dialogs

---

Alloy/template/gitignore.txt
templates/default/.gitignore
templates/two_tabbed/.gitignore

**JIRA:**: https://jira.appcelerator.org/browse/ALOY-1626
Reverts appcelerator/alloy#883
@feons In which Alloy version can we ship this with?

[ALOY-1626] Revert "Add plugins/ti.alloy to gitignore"

---

Alloy/commands/compile/compilerUtils.js
hooks/alloy.js

**JIRA:** https://jira.appcelerator.org/browse/ALOY-1631
From [documentation](https://docs.appcelerator.com/platform/latest/#!/guide/Alloy_Themes)
> To use a theme, add it to your Alloy project's config.json file with "theme" as the key and the name of the theme folder as the value
For my application I need to apply different themes for customers, so it would be nice to have ability to define theme from command line.

[ALOY-1631] Add "theme" CLI parameter

---

Alloy/utils.js

https://jira.appcelerator.org/browse/ALOY-1620
Rather than just change the Buffer usage, I just replaced the custom logic with an fs-extra call. I did some fairly unscientific testing and there's no noticeable performance difference

[ALOY-1620] Replace custom copy file logic with fs-extra copySync call

---

Alloy/commands/compile/Orphanage.js
Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/index.js
Alloy/commands/extract-i18n/index.js
Alloy/commands/generate/targets/style.js
Alloy/utils.js
CHANGELOG.md
package-lock.json
package.json

JIRA: https://jira.appcelerator.org/browse/ALOY-1644
walk-sync always returns posix separators regardless of the platform, which causes comparisons to fail on Windows
Fixes ALOY-1644
Note that I've not done this on all walkSync calls, only the ones that reference the file path.

fix: normalize path from walkSync call before using in comparisons

---

Alloy/commands/compile/index.js
CHANGELOG.md
package-lock.json
package.json

https://jira.appcelerator.org/browse/ALOY-1650
We use a regex to check exclude certain directories from being optimized here, that regex is constructed using posix path separators so by normalizing to windows separators we are no longer matching the regex
Fixes ALOY-1650

fix(compile): do not normalize filepaths to be correct for platform in optimizeCompiledCode

---

Alloy/commands/compile/parsers/Alloy.Abstract._ItemContainer.js
CHANGELOG.md

On iOS compiling we get warning `Additional views in null only supported on Android` with code
```xml
<AlertDialog id="confirmAlertDialog">
<View platform="android">
<Label>Android only!!</Label>
</View>
</AlertDialog>
```

[ALOY-1535] Remove unnecessary warning message with iOS

---

Alloy/lib/alloy/sync/sql.js

**JIRA**: https://jira.appcelerator.org/browse/TIMOB-27053
**Description**
On Windows and Android we explicitly bound a reference to the ResultSet's field method to the instance
We did not on iOS, so changes to be more compliant on master resulted in an error
due to `this` being implicitly the global and not the ResultSet instance.
This is effectively the same issue as TIMOB-20577
Eliminated the redirection used to call the method altogether in favor of the more straight-forward
`rs.field(i)`.
Fixes TIMOB-27053

fix(ios): fix fetch() on iOS due to unbound call to ResultSet.field

---

.vscode/launch.json
Alloy/commands/compile/parsers/Alloy.Abstract._ItemContainer.js
Alloy/commands/compile/parsers/Ti.UI.OptionDialog.js
CHANGELOG.md

Setting these values to undefined on Android causes a runtime error when it attempts to build the event
Fixes [ALOY-1653](https://jira.appcelerator.org/browse/ALOY-1653)

fix(optiondialog): do not set cancel and destructive properties if not in attributes

---

Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/styler.js
Alloy/grammar/tss.js
Alloy/grammar/tss.pegjs

https://jira.appcelerator.org/browse/ALOY-1316
Not sure if it's a good idea to treat `'$.args.*'` as an expression. Maybe we should differentiate a `string` and a js `expression` when setting properties.

[ALOY-1316] Support use of $.args.* in any XML attribute or TSS property

---

Alloy/commands/compile/index.js
Alloy/commands/compile/sourceMapper.js
Alloy/utils.js
test/specs/optimizer.js

https://jira.appcelerator.org/browse/ALOY-1612

fix: improve debugging of applications in third party tools and Studio

---

Alloy/template/config.json

Removing os:windows from config.json due to dropping Windows support since SDK 9.0

Remove os:windows from config.json

---

Alloy/builtins/animation.js
Alloy/template/lib/alloy.js
CHANGELOG.md

JIRA: [ALOY-1720](https://jira.appcelerator.org/browse/ALOY-1720)
* Matrix calls - As we were using the version to basically do feature detection I went with checking if the functions existed rather than using an SDK version check
* M2_320 check - As we've dropped support for Mobilweb _and_ 3.2.0 is years old, I went with removing the version check and just having it be a `OS_MOBILEWEB` check

refactor: fix invalid version comparisons

---

Alloy/template/app.js

**JIRA:**
https://jira.appcelerator.org/browse/ALOY-1732
**Summary:**
This change is needed by [TIMOB-27896](https://jira.appcelerator.org/browse/TIMOB-27896) to support executing the "app.js" in the background before the app is capable of hosting UI. It also supports open the root window more than once when new UI sessions are created, which happens on Android when you back out of the app and relaunch for the same app process.

feat: add ability to run in background without UI

---

Alloy/commands/compile/index.js
Alloy/template/alloy.bootstrap.js
Alloy/template/app.js
CHANGELOG.md
package-lock.json
package.json

Fixes [ALOY-1734](https://jira.appcelerator.org/browse/ALOY-1734)
* `alloy.bootstrap.js` will be loaded at startup before the `app.js`, this ensures that the globals are correctly configured _before_ the `app.js` is even executed.
* Check if the globals exist in the `app.js` and set them if they don't, this should keep us compatible with SDKs pre-7.5.0 (i.e. those without the bootstrap feature, if you're using an SDK that old ... please, please, please update ASAP)
Test steps - see jira

fix(runtime): use bootstrap mechanism to load globals rather than setting in the alloy.js file

---

Alloy/commands/compile/parsers/Ti.UI.ListSection.js

JIRA: https://jira.appcelerator.org/browse/AC-6585
Use `items = ` instead of deprecated `setItems()`. Will get rid of the warnings.

fix: Use items in ListSection 

---

Alloy/commands/compile/parsers/Alloy.Require.js
CHANGELOG.md
package-lock.json
package.json

Fixes [ALOY-1738](https://jira.appcelerator.org/browse/ALOY-1738)
cc @brentonhouse I've verified that [brentonhouse/alloy-widget-test](https://github.com/brentonhouse/alloy-widget-test) still work with this change, do you have any other usage of top levels widgets?

fix: handle widget case explicitly and revert back to previous default behaviour

---

package.json
test/lib/JunitReporter.js

Replaces the test usage of mkdirp with usage of `mkdirpSync` from fs-extra. This is used in the junit file writing, so if Jenkins picks that file up ok, and danger reports the stats ok we're groovy

build: replace mkdirp with fs-extra

---

Alloy/commands/compile/BuildLog.js
Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/index.js
Alloy/commands/compile/sourceMapper.js
Alloy/commands/extract-i18n/i18nHandler.js
Alloy/commands/generate/targets/widget.js
Alloy/commands/new/index.js
Alloy/utils.js
jakelib/app.jake
package-lock.json
package.json
test/lib/testUtils.js
test/specs/compilefile.js
test/specs/new.js
tools/create_generated_code.js

The file permissions that get set are ultimately only preserved when alloy creates the files in
Resources, when the SDK copies the files over to the application binary these ultimately become the
system defaults. Furthermore, files were incorrectly being given 755 permissions on first creation
and then changed to 644 on an incremental build.
We will now just use the node defaults for these files rather than setting them, files will be
given 644 and folders will be given 777
Tested against kitchensink and pko and I'm seeing no negative consequences of doing this

refactor: remove chmodr

---

Alloy/commands/compile/parsers/Alloy.Require.js

We now look for whether there are any sibling nodes alongside the Widget tag, if there are then
we should not make this Widget the top level view
Fixes ALOY-1743

fix: improve check around whether widget is only tag in the view

---

Alloy/commands/compile/parsers/Ti.UI.NavigationWindow.js

After https://github.com/appcelerator/titanium_mobile/pull/11166 it is allowed to have a TabGroup inside a NavigationWindow but Alloy currently doesn't allow it. 
This change will fix the compiling error
```
<Alloy>
<NavigationWindow>
<TabGroup title="Tabgroup">
<Tab title="tab">
<Window/>
</Tab>
<Tab title="tab">
<Window/>
</Tab>
</TabGroup>
</NavigationWindow>
</Alloy>
```

fix(compile): allow TabGroup as child of a NavigationWindow

---

Alloy/commands/compile/compilerUtils.js

It seems these files never had sourcemaps generated for them, so debuggers weren't able to point back to the correct file a user was attempting to debug a file.

fix(compile): generate source maps for lib files in widgets

---

.github/workflows/build.yml
test/lib/testUtils.js
test/specs/compile.js

Setups GitHub actions and also does the following in tests:
* Adds `./bin/alloy` to process.env in tests to ensure we're always using the local alloy
* Removes the testing of mobileweb in (mostly failed) attempt to reduce the test time (cut around 5 minutes off)

ci: add actions workflow

---

Alloy/template/config.json
templates/default/app/config.json
templates/two_tabbed/app/config.json
templates/webpack-default/app/config.json

This way new apps will use the newer Backbone version and not the very old default 0.9.2! Old/existing apps will still use 0.9.2 when no other version is defined and still work. Raising the constant in https://github.com/appcelerator/alloy/blob/master/Alloy/common/constants.js#L49 could break existing apps.

feat(all): set default backbone version

---

Alloy/commands/compile/sourceMapper.js

This would lead to technically invalid paths on Windows systems that could then not be consumed correctly

fix(compile/sourcemap): use path.join rather than manually constructing a path

---

hooks/alloy.js

This updates the Alloy compile hook so that if the alloy CLI cannot be found rather than outputting the below confusing error that doesn't inform the user what the problem is
```text
[INFO]  Executing Alloy compile: /Users/awam/.nvm/versions/node/v16.13.0/bin/node  compile /Users/awam/Documents/Appcelerator_Studio_Workspace/plainalloy/app --config platform=android,version=0,simtype=none,devicefamily=none,deploytype=development,target=emulator
[DEBUG] node:internal/modules/cjs/loader:936
[DEBUG]   throw err;
[DEBUG]   ^
[ERROR] : Cannot find module '/Users/awam/Documents/Appcelerator_Studio_Workspace/plainalloy/undefined'
[DEBUG]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
[DEBUG]     at Function.Module._load (node:internal/modules/cjs/loader:778:27) …
```

fix(compile/hook): error if unable to find the alloy cli

---

Alloy/commands/new/index.js

one part for: https://github.com/tidev/titanium_mobile/issues/13241
copying an existing semantic file when converting classic -> alloy
**Test**
* `ti create`
* create `Resources/semantic.colors.json` or use https://github.com/tidev/titanium_mobile/pull/13326
* `alloy new`
* check if `semantic.colors.json` exists in `app/assets/`

feat: copy semantic file

---

.github/workflows/build.yml
.github/workflows/publish.yml
CONTRIBUTING.md

This adds a publish action similar to the others that will publish the alloy package when a new release is created.
I've also added a `CONTRIBUTING.md` file that describes how to do this, it totally needs fleshing out some more but maybe that can be done after the release.
It also removes the `-b latest` usage from the test matrix cos it no longer exists.

ci: add github action to publish alloy

---

Alloy/commands/compile/parsers/Ti.UI.PickerColumn.js

fixes https://github.com/tidev/alloy/issues/1348
Need to test it but it looks correct since it is using an old method instead of the getter property

fix(all): remove getter in PickerColumn parser

---

Alloy/commands/compile/parsers/Ti.UI.Android.CollapseToolbar.ContentView.js
Alloy/commands/compile/parsers/Ti.UI.Android.CollapseToolbar._ProxyProperty.js
Alloy/commands/compile/parsers/Ti.UI.Android.CollapseToolbar.js
Alloy/common/constants.js

* Add `CollapseToolbar` to Alloy (copied over from `DrawerLayout`)
needed for https://github.com/tidev/titanium_mobile/pull/13760
```xml
<Alloy>
<Window>
<CollapseToolbar platform="android">
<ContentView>
<View backgroundColor="red" height="Ti.UI.SIZE">
<Label>test</Label>
</View>
</ContentView>
</CollapseToolbar>
</Window>
</Alloy>
```

feat(android): add collapseToolbar support

---

test/lib/testUtils.js

Executables are resolved first found in the path iirc, so prefixing is the right thing to do

test: prefix bin to path to ensure local alloy is used

---

Alloy/commands/compile/parsers/Ti.UI.Android.CollapseToolbar.ContentView.js
Alloy/commands/compile/parsers/Ti.UI.Android.CollapseToolbar.js

**Changes**
* add missing includes.
**Fixes**
Being able to use `<ContentView ns="Ti.UI.Android.CollapseToolbar">` in Alloy again.
---
**Sidenote**
Still have to find out why `isTitanium` is false and the `Titanium` namespace is not available in
https://github.com/tidev/alloy/blob/master/Alloy/common/constants.js#L238-L239
it used to work.

fix: missing includes

---

Alloy/common/constants.js
Alloy/lib/alloy/backbone/1.6.0/backbone.js

when switching from Backbone 1.5.0 to 1.6.0 in the last PR I forgot to update these two files in order to use underscore functions.
I most Backbone stuff was working but functions like `findWhere` didn't work.
After this fix everything is working again

fix: backbone 1.6.0 fixes
