tidev/alloy

test/apps/advanced/themes/_generated/android/alloy/controllers/index.js
test/apps/advanced/themes/_generated/blackberry/alloy/controllers/dialog.js
test/apps/advanced/themes/_generated/blackberry/alloy/controllers/index.js
test/apps/advanced/themes/_generated/ios/alloy/controllers/index.js
test/apps/advanced/themes/_generated/mobileweb/alloy/controllers/index.js
test/specs/install.js

Resolves https://jira.appcelerator.org/browse/ALOY-1222

[ALOY-1222] Fix failing tests: install, compile of advanced/themes

---

Alloy/commands/compile/Orphanage.js
Alloy/commands/compile/index.js

https://jira.appcelerator.org/browse/ALOY-1206

[ALOY-1206] Regenerate controllers when changing distr. target

---

samples/rss/controllers/index.js
samples/rss/views/ios/detail.xml

https://jira.appcelerator.org/browse/ALOY-1215

[ALOY-1215] Alloy RSS Reader sample does not work on iPad

---

Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/index.js
Alloy/commands/compile/parsers/Alloy.Abstract._ItemArray.js
Alloy/commands/compile/parsers/Ti.Map.View.js
Alloy/commands/compile/parsers/Ti.UI.DashboardView.js
Alloy/commands/compile/parsers/Ti.UI.ListSection.js
Alloy/commands/compile/parsers/Ti.UI.PickerColumn.js
Alloy/commands/compile/parsers/Ti.UI.ScrollableView.js
Alloy/commands/compile/parsers/Ti.UI.TableView.js
Alloy/commands/compile/parsers/default.js
test/apps/testing/ALOY-1127/controllers/index.js
test/apps/testing/ALOY-1127/models/test.js
test/apps/testing/ALOY-1127/styles/index.tss
test/apps/testing/ALOY-1127/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1127

[ALOY-1127] data binding work with formFactor

---

Alloy/commands/compile/parsers/Ti.UI.TextArea.js
Alloy/commands/compile/parsers/Ti.UI.TextField.js
test/apps/testing/ALOY-1152/controllers/index.js
test/apps/testing/ALOY-1152/styles/index.tss
test/apps/testing/ALOY-1152/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1152

[ALOY-1152] - Alloy 1.5.0 RC3: Compiler fails on TextArea with child control

---

Alloy/commands/info/index.js
test/specs/info.js

https://jira.appcelerator.org/browse/ALOY-1113

[ALOY-1113] fix case on alloy info adapters command

---

Alloy/commands/compile/styler.js
test/apps/testing/ALOY-1219/alloy.js
test/apps/testing/ALOY-1219/config.json
test/apps/testing/ALOY-1219/controllers/index.js
test/apps/testing/ALOY-1219/styles/app.tss
test/apps/testing/ALOY-1219/styles/index.tss
test/apps/testing/ALOY-1219/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1219

[ALOY-1219] regex change to support {{ }}

---

Alloy/lib/alloy.js

https://jira.appcelerator.org/browse/ALOY-1174

[ALOY-1174] Fix to allow the use of promises in sync adapters

---

Alloy/template/config.json

https://jira.appcelerator.org/browse/ALOY-1138

[ALOY-1138] add missing config.json template file

---

Alloy/commands/compile/index.js
test/specs/compile.js

https://jira.appcelerator.org/browse/ALOY-1228

[ALOY-1228] Selective compilation can fail with platform-specific controllers

---

Alloy/commands/compile/compilerUtils.js
Alloy/commands/compile/index.js
Alloy/common/constants.js
hooks/alloy.js

https://jira.appcelerator.org/browse/ALOY-858

[ALOY-858] Theme i18n and platform

---

hooks/alloy.js

https://jira.appcelerator.org/browse/ALOY-1232

[ALOY-1232] : --deploy-type ignored on android builds for emulator and device

---

Alloy/commands/generate/generateUtils.js
Alloy/commands/generate/index.js
Alloy/common/constants.js
Alloy/utils.js

https://jira.appcelerator.org/browse/ALOY-1238

[ALOY-1238] Can't re-create index controller after renaming original one

---

hooks/alloy.js

also handles the case of no global installation of alloy

[CLI-461] properly handle windows node/alloy paths

---

Alloy/commands/compile/compilerUtils.js

Fixes: https://jira.appcelerator.org/browse/ALOY-1021

Allow for Alloy.Globals and Alloy.CFG in views

---

Alloy/commands/compile/compilerUtils.js
Alloy/lib/alloy/controllers/BaseController.js
test/apps/testing/ALOY-1237/config.json
test/apps/testing/ALOY-1237/controllers/index.js
test/apps/testing/ALOY-1237/styles/index.tss
test/apps/testing/ALOY-1237/views/index.xml

Added the get/remove event methods on defined in XML. But not modify $.destroy(). It looks like a $.destroy() for data binding.

[ALOY-1237] Added getEvent, getEvents, removeEvent and removeEvents methods in BaseController.js

---

hooks/alloy.js

https://jira.appcelerator.org/browse/ALOY-1272

[ALOY-1272] Building an alloy project with Titanium CLI on Windows fails 1_6_X

---

hooks/alloy.js

https://jira.appcelerator.org/browse/ALOY-1272

[ALOY-1272] Building an alloy project with Titanium CLI on Windows fails

---

CHANGELOG.md

Update Release Notes

---

test/apps/advanced/inheritance/styles/index.tss
test/apps/advanced/inheritance/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1214

[ALOY-1214] Button in Inheritance sample app difficult to click on iOS

---

samples/todo/controllers/add.js
samples/todo/models/todo.js
test/apps/models/todo/controllers/add.js
test/apps/models/todo/models/todo.js

https://jira.appcelerator.org/browse/ALOY-1226

[ALOY-1226] ToDo sample app validate() fails to prevent empty items from being added

---

package.json

https://jira.appcelerator.org/browse/ALOY-1239

[ALOY-1239] Set Node 0.10 as minimum supported version

---

CHANGELOG.md

https://jira.appcelerator.org/browse/ALOY-1301

[ALOY-1301] Updated CHANGELOG

---

hooks/alloy.js
package.json

https://jira.appcelerator.org/browse/CLI-804

[CLI-804] Windows: Cannot build Alloy project on Windows 10

---

Alloy/commands/compile/compilerUtils.js

https://jira.appcelerator.org/browse/ALOY-1210

[ALOY-1210] Add support for DIST in the Project Configuration File

---

Alloy/lib/alloy.js

https://jira.appcelerator.org/browse/ALOY-1285

[ALOY-1285] TSS conditional statement is ignored by items dynamically generated on runtime

---

Alloy/commands/compile/parsers/Ti.UI.TableViewSection.js

https://jira.appcelerator.org/browse/ALOY-1241

[ALOY-1241] Widgets are initialized twice in TableViewSection

---

hooks/alloy.js
package.json

https://jira.appcelerator.org/browse/CLI-817

[CLI-817] add version to hook

---

Alloy/commands/compile/parsers/Ti.UI.Picker.js
package.json

https://jira.appcelerator.org/browse/ALOY-1310

[ALOY-1310] Alloy: Picker not working in ListView template

---

Alloy/commands/compile/index.js
package.json

https://jira.appcelerator.org/browse/ALOY-1317

[ALOY-1317] Default top-level ID doesn't take if-attribute into account

---

Alloy/commands/compile/parsers/Ti.Android.MenuItem.js
package.json

https://jira.appcelerator.org/browse/ALOY-1283

[ALOY-1283] ActionView views with an ID cannot be found under $

---

Alloy/commands/compile/index.js
Alloy/commands/compile/parsers/Ti.UI.Tab.js
Alloy/commands/compile/parsers/Ti.UI.iOS.SplitWindow.js
Alloy/common/constants.js
package.json
test/apps/testing/ALOY-846/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-846/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1264

[ALOY-1264] Support New iOS SplitWindow in XML Markup

---

Alloy/commands/compile/parsers/Ti.UI.Android.CardView.js
Alloy/common/constants.js
package.json
test/apps/testing/ALOY-1319/controllers/index.js
test/apps/testing/ALOY-1319/styles/index.tss
test/apps/testing/ALOY-1319/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1319

[ALOY-1319] Support CardView in XML

---

Alloy/commands/compile/index.js
package.json
test/apps/advanced/alloy_jmk/alloy.jmk

https://jira.appcelerator.org/browse/ALOY-1311

[ALOY-1311] Alloy.jmk compile:app.js event never fires

---

Alloy/commands/compile/styler.js
package.json
test/apps/testing/ALOY-1320/controllers/index.js
test/apps/testing/ALOY-1320/lib/customlbl.js
test/apps/testing/ALOY-1320/styles/index.tss
test/apps/testing/ALOY-1320/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1320

[ALOY-1320] Styles not applied when an element uses another namespace

---

Alloy/commands/compile/parsers/Alloy.Abstract.Actions.js
Alloy/commands/compile/parsers/Alloy.Abstract.Preview.js
Alloy/commands/compile/parsers/Alloy.Abstract._ProxyProperty.js
Alloy/commands/compile/parsers/Ti.UI.ListView.js
Alloy/commands/compile/parsers/Ti.UI.TableView.js
Alloy/commands/compile/parsers/Ti.UI.iOS.PreviewAction.js
Alloy/commands/compile/parsers/Ti.UI.iOS.PreviewActionGroup.js
Alloy/commands/compile/parsers/Ti.UI.iOS.PreviewContext.js
Alloy/commands/compile/parsers/default.js
Alloy/common/constants.js
package.json
test/apps/testing/ALOY-1325/controllers/index.js
test/apps/testing/ALOY-1325/styles/index.tss
test/apps/testing/ALOY-1325/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1325

[ALOY-1325] Add PreviewContext element to XML views

---

Alloy/lib/alloy.js
package.json
test/apps/advanced/device_query/specs/index.js

https://jira.appcelerator.org/browse/ALOY-1331

[ALOY-1331] Windows: App crashes with 'Cannot find variable: OS_BLACKBERRY

---

Alloy/commands/compile/index.js
package.json

https://jira.appcelerator.org/browse/ALOY-1323

[ALOY-1323] Alloy: module-tag in Alloy element effects all controller views

---

Alloy/commands/compile/index.js
Alloy/template/lib/alloy.js
package.json

https://jira.appcelerator.org/browse/ALOY-1332

[ALOY-1332] Alloy.version does not match actual version

---

Alloy/commands/compile/parsers/Ti.UI.Label.js
package.json
test/apps/testing/ALOY-961/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1345

[ALOY-1345] iOS Attributed Strings are not showing

---

Alloy/template/controller.js

https://jira.appcelerator.org/browse/ALOY-1346

[ALOY-1346] Controller template should no longer declare args variable

---

docs/apidoc/alloy.js
package.json

https://jira.appcelerator.org/browse/TIDOC-2425

[TIDOC-2425] Docs: broken page /api/Alloy-method-createModel

---

Alloy/commands/compile/parsers/Alloy.Abstract.Item.js
Alloy/commands/compile/parsers/Alloy.Abstract.Items.js
Alloy/commands/compile/parsers/Alloy.Abstract._ItemArray.js
Alloy/commands/compile/parsers/Ti.UI.iOS.MenuPopup.js
Alloy/common/constants.js
test/apps/testing/ALOY-1357/controllers/index.js
test/apps/testing/ALOY-1357/styles/index.tss
test/apps/testing/ALOY-1357/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1357

[ALOY-1357] Support Ti.UI.iOS.MenuPopup in XML

---

Alloy/common/constants.js
test/apps/testing/ALOY-1358/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1358/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1358/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1358/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1358/controllers/index.js
test/apps/testing/ALOY-1358/styles/index.tss
test/apps/testing/ALOY-1358/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1358

[ALOY-1358] Support Ti.UI.iOS.BlurView in XML

---

Alloy/common/constants.js
test/apps/testing/ALOY-1356/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1356/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1356/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1356/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1356/controllers/index.js
test/apps/testing/ALOY-1356/styles/index.tss
test/apps/testing/ALOY-1356/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1356

[ALOY-1356] Add support for LivePhotoView under Ti.UI.iOS namespace

---

Alloy/commands/compile/ast/controller.js
Alloy/commands/compile/index.js
Alloy/common/constants.js
test/apps/testing/ALOY-1360/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1360/_generated/android/alloy/controllers/myBaseController.js
test/apps/testing/ALOY-1360/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1360/_generated/ios/alloy/controllers/myBaseController.js
test/apps/testing/ALOY-1360/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1360/_generated/mobileweb/alloy/controllers/myBaseController.js
test/apps/testing/ALOY-1360/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1360/_generated/windows/alloy/controllers/myBaseController.js
test/apps/testing/ALOY-1360/controllers/index.js
test/apps/testing/ALOY-1360/styles/myBaseController.tss
test/apps/testing/ALOY-1360/views/index.xml
test/apps/testing/ALOY-1360/views/myBaseController.xml

pull request for https://jira.appcelerator.org/browse/AC-642

Added support for baseController attribute in Alloy xml tag

---

Alloy/commands/compile/compilerUtils.js

https://jira.appcelerator.org/browse/ALOY-1254

[ALOY-1254] Alloy: Support model transform() method for collection-view binding

---

Alloy/commands/compile/index.js
Alloy/commands/compile/styler.js
Alloy/common/constants.js
test/apps/testing/ALOY-1474/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1474/_generated/android/alloy/models/Transformer.js
test/apps/testing/ALOY-1474/_generated/android/alloy/models/Transformless.js
test/apps/testing/ALOY-1474/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1474/_generated/ios/alloy/models/Transformer.js
test/apps/testing/ALOY-1474/_generated/ios/alloy/models/Transformless.js
test/apps/testing/ALOY-1474/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1474/_generated/mobileweb/alloy/models/Transformer.js
test/apps/testing/ALOY-1474/_generated/mobileweb/alloy/models/Transformless.js
test/apps/testing/ALOY-1474/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1474/_generated/windows/alloy/models/Transformer.js
test/apps/testing/ALOY-1474/_generated/windows/alloy/models/Transformless.js
test/apps/testing/ALOY-1474/controllers/index.js
test/apps/testing/ALOY-1474/models/transformer.js
test/apps/testing/ALOY-1474/models/transformless.js
test/apps/testing/ALOY-1474/styles/index.tss
test/apps/testing/ALOY-1474/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1474

[ALOY-1474] [ALOY-1368] Fixes regression in model data binding without model transform() and bug with

---

Alloy/commands/new/index.js
package.json

https://jira.appcelerator.org/browse/ALOY-1492

[ALOY-1492] - Fix no such file or directory when doing "alloy new"

---

Alloy/commands/new/index.js

https://jira.appcelerator.org/browse/ALOY-1492

[ALOY-1492] Fix no such file or directory when doing "alloy new"

---

Alloy/common/constants.js
test/apps/testing/ALOY-1494/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1494/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1494/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1494/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1494/controllers/index.js
test/apps/testing/ALOY-1494/styles/index.tss
test/apps/testing/ALOY-1494/views/index.xml

JIRA: https://jira.appcelerator.org/browse/ALOY-1494

[ALOY-1494] Add Ti.UI.iOS.Stepper XML support

---

test/apps/testing/ALOY-1480/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1480/_generated/android/alloy/models/Model-a.js
test/apps/testing/ALOY-1480/_generated/android/alloy/models/Modelb.js
test/apps/testing/ALOY-1480/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1480/_generated/ios/alloy/models/Model-a.js
test/apps/testing/ALOY-1480/_generated/ios/alloy/models/Modelb.js
test/apps/testing/ALOY-1480/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1480/_generated/mobileweb/alloy/models/Model-a.js
test/apps/testing/ALOY-1480/_generated/mobileweb/alloy/models/Modelb.js
test/apps/testing/ALOY-1480/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1480/_generated/windows/alloy/models/Model-a.js
test/apps/testing/ALOY-1480/_generated/windows/alloy/models/Modelb.js

@feons test app 1480 was missing generated code

Add generated code

---

Alloy/commands/compile/styler.js
test/apps/testing/ALOY-1503/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1503/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1503/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1503/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1503/controllers/index.js
test/apps/testing/ALOY-1503/styles/index.tss
test/apps/testing/ALOY-1503/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1503

[ALOY-1503] After Alloy compile, property which has array disappear.

---

Alloy/commands/compile/compilerUtils.js
package.json

https://jira.appcelerator.org/browse/ALOY-1508

[ALOY-1508] iOS: Localised splash screen is not visible

---

Alloy/commands/compile/parsers/Ti.UI.TableView.js

JIRA: https://jira.appcelerator.org/browse/ALOY-1510

[ALOY-1510] Fix child-node detection of platfrom

---

Alloy/lib/alloy/sync/sql.js
test/apps/testing/ALOY-1493/controllers/index.js
test/apps/testing/ALOY-1493/models/test.js
test/apps/testing/ALOY-1493/views/index.xml

**JIRA**: https://jira.appcelerator.org/browse/ALOY-1493
example:
```javascript
exports.definition = {
config: {
columns: {},
adapter: {
type: "sql",
collection_name: "mytable",
db_file: function() {
var myFile = Titanium.Filesystem.getFile(Titanium.Filesystem.applicationDataDirectory, 'file1.sql');
return myFile.exists() ? myFile.nativePath : Titanium.Filesystem.applicationDataDirectory + 'file2.sql';
},
db_name: "projectsDB",
idAttribute: "UserID",
remoteBackup: false
}
}
};
```

[ALOY-1493] db_file now accepting function

---

Alloy/commands/compile/parsers/Ti.UI.ScrollView.js
package.json
test/apps/testing/ALOY-1519/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1519/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1519/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1519/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1519/controllers/index.js
test/apps/testing/ALOY-1519/styles/index.tss
test/apps/testing/ALOY-1519/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1519

[ALOY-1519]  Support iOS 10 <RefreshControl> tag in Ti.UI.ScrollView

---

Alloy/commands/compile/compilerUtils.js
package.json
test/apps/testing/ALOY-1526/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1526/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1526/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1526/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1526/controllers/index.js
test/apps/testing/ALOY-1526/styles/index.tss
test/apps/testing/ALOY-1526/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1526

[ALOY-1526] Special text property value is not parsed correctly

---

Alloy/commands/compile/parsers/Alloy.Abstract.ItemTemplate.js
Alloy/commands/compile/parsers/Alloy.Abstract._ItemContainer.js
test/apps/testing/ALOY-1527/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1527/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1527/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1527/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1527/controllers/index.js
test/apps/testing/ALOY-1527/styles/index.tss
test/apps/testing/ALOY-1527/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1527

[ALOY-1527] Cannot use Ti.UI.iOS.TabbedBar in ListView template

---

Alloy/commands/compile/parsers/Alloy.Abstract._ItemArray.js
test/apps/testing/ALOY-1541/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1541/_generated/android/alloy/controllers/navbar.js
test/apps/testing/ALOY-1541/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1541/_generated/ios/alloy/controllers/navbar.js
test/apps/testing/ALOY-1541/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1541/_generated/mobileweb/alloy/controllers/navbar.js
test/apps/testing/ALOY-1541/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1541/_generated/windows/alloy/controllers/navbar.js
test/apps/testing/ALOY-1541/controllers/index.js
test/apps/testing/ALOY-1541/styles/index.tss
test/apps/testing/ALOY-1541/views/index.xml
test/apps/testing/ALOY-1541/views/navbar.xml

https://jira.appcelerator.org/browse/ALOY-1541

[ALOY-1541] XML: Require LeftNavButtons/RightNavButtons not working

---

Alloy/template/lib/alloy.js

https://jira.appcelerator.org/browse/ALOY-1504

[ALOY-1504] ERROR: Alloy is not defined

---

Alloy/commands/compile/index.js

https://jira.appcelerator.org/browse/ALOY-1540

[ALOY-1540] npm node_modules are erroring when compiling

---

Alloy/commands/compile/compilerUtils.js
test/apps/testing/ALOY-1545/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1545/_generated/android/alloy/models/Demo.js
test/apps/testing/ALOY-1545/_generated/android/alloy/widgets/foo/controllers/widget.js
test/apps/testing/ALOY-1545/_generated/android/alloy/widgets/foo/styles/widget.js
test/apps/testing/ALOY-1545/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1545/_generated/ios/alloy/models/Demo.js
test/apps/testing/ALOY-1545/_generated/ios/alloy/widgets/foo/controllers/widget.js
test/apps/testing/ALOY-1545/_generated/ios/alloy/widgets/foo/styles/widget.js
test/apps/testing/ALOY-1545/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1545/_generated/mobileweb/alloy/models/Demo.js
test/apps/testing/ALOY-1545/_generated/mobileweb/alloy/widgets/foo/controllers/widget.js
test/apps/testing/ALOY-1545/_generated/mobileweb/alloy/widgets/foo/styles/widget.js
test/apps/testing/ALOY-1545/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1545/_generated/windows/alloy/models/Demo.js
test/apps/testing/ALOY-1545/_generated/windows/alloy/widgets/foo/controllers/widget.js
test/apps/testing/ALOY-1545/_generated/windows/alloy/widgets/foo/styles/widget.js
test/apps/testing/ALOY-1545/config.json
test/apps/testing/ALOY-1545/controllers/index.js
test/apps/testing/ALOY-1545/models/Demo.js
test/apps/testing/ALOY-1545/styles/index.tss
test/apps/testing/ALOY-1545/views/index.xml
test/apps/testing/ALOY-1545/widgets/foo/controllers/widget.js
test/apps/testing/ALOY-1545/widgets/foo/views/widget.xml
test/apps/testing/ALOY-1545/widgets/foo/widget.json

https://jira.appcelerator.org/browse/ALOY-1545

[ALOY-1545] Broken Widget event translation

---

Alloy/commands/compile/sourceMapper.js
CHANGELOG.md
package.json
test/specs/optimizer.js
yarn.lock

https://jira.appcelerator.org/browse/ALOY-1565
- Bump version, add bgfix to changelog

Fix [ALOY-1665] KitchenSink v2 errors out on iOS

---

Alloy/commands/compile/ast/optimizer-plugin.js

https://jira.appcelerator.org/browse/ALOY-1566

[ALOY-1566] OS_* declaration should not choke compile

---

package.json
test/specs/optimizer.js

Code minification has been removed from optimising step, some of the tests should be updated.

fix optimizer tests

---

Alloy/commands/compile/index.js
package.json

https://jira.appcelerator.org/browse/ALOY-1572

[ALOY-1572] Alloy doesn't compile external app.js 1_9_X

---

Alloy/commands/compile/index.js

https://jira.appcelerator.org/browse/ALOY-1572

[ALOY-1572] Alloy doesn't compile external app.js

---

Alloy/commands/compile/compilerUtils.js
test/apps/testing/ALOY-1564/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1564/_generated/android/alloy/controllers/products.js
test/apps/testing/ALOY-1564/_generated/android/alloy/models/Demo.js
test/apps/testing/ALOY-1564/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1564/_generated/ios/alloy/controllers/products.js
test/apps/testing/ALOY-1564/_generated/ios/alloy/models/Demo.js
test/apps/testing/ALOY-1564/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1564/_generated/mobileweb/alloy/controllers/products.js
test/apps/testing/ALOY-1564/_generated/mobileweb/alloy/models/Demo.js
test/apps/testing/ALOY-1564/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1564/_generated/windows/alloy/controllers/products.js
test/apps/testing/ALOY-1564/_generated/windows/alloy/models/Demo.js
test/apps/testing/ALOY-1564/controllers/index.js
test/apps/testing/ALOY-1564/controllers/products.js
test/apps/testing/ALOY-1564/models/Demo.js
test/apps/testing/ALOY-1564/styles/index.tss
test/apps/testing/ALOY-1564/views/index.xml
test/apps/testing/ALOY-1564/views/products.xml

https://jira.appcelerator.org/browse/ALOY-1564

[ALOY-1564] Broken Require data-binding event translation

---

Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout.CenterView.js
Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout.LeftView.js
Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout.RightView.js
Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout._ProxyProperty.js
Alloy/common/constants.js
test/apps/testing/ALOY-1579/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1579/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1579/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1579/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1579/controllers/index.js
test/apps/testing/ALOY-1579/styles/index.tss
test/apps/testing/ALOY-1579/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1579

[ALOY-1579] Support Titanium.UI.Android.DrawerLayout 1_9_X

---

Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout.CenterView.js
Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout.LeftView.js
Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout.RightView.js
Alloy/commands/compile/parsers/Ti.UI.Android.DrawerLayout._ProxyProperty.js
Alloy/common/constants.js
test/apps/testing/ALOY-1579/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1579/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1579/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1579/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1579/controllers/index.js
test/apps/testing/ALOY-1579/styles/index.tss
test/apps/testing/ALOY-1579/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1579

[ALOY-1579] Support Titanium.UI.Android.DrawerLayout

---

Alloy/alloy.js
Alloy/template/config.json
package.json

https://jira.appcelerator.org/browse/CLI-1272

[CLI-1272] remove "mobileweb" from config template

---

templates/default/app/config.json
templates/two_tabbed/app/config.json

https://jira.appcelerator.org/browse/CLI-1272

[CLI-1272] removed mobileweb and blackberry from studio config.json template

---

Alloy/commands/compile/ast/optimizer-plugin.js
package-lock.json
package.json
test/specs/optimizer.js

https://jira.appcelerator.org/browse/ALOY-1590

[ALOY-1590] OS_IOS assigned to a variable causes a crash

---

Alloy/lib/alloy/backbone/1.3.3/backbone.js
package-lock.json
package.json

https://jira.appcelerator.org/browse/ALOY-1534
Still not set as default version, due to breaking change in the Backbone library from 0.9 to 1.3, existing apps using backbone@0.9 may not run without modification.

[ALOY-1534] Add support for Backbone 1.3.3

---

Alloy/builtins/measurement.js

**JIRA**:  https://jira.appcelerator.org/browse/ALOY-1592

[ALOY-1592] Reimplement measurement by convertUnits

---

Alloy/builtins/measurement.js

https://jira.appcelerator.org/browse/ALOY-1592

Fix spaces in builtins/measurement.js

---

Alloy/common/constants.js
Alloy/lib/alloy/underscore.js
CHANGELOG.md
package-lock.json
package.json

https://jira.appcelerator.org/browse/ALOY-1534
- add Backbone 1.3.3 to supported list
- update Underscore to 1.8.3
- update changelog

[ALOY-1534] Add support for Backbone 1.3.3 and Underscore 1.8.3

---

Alloy/commands/compile/index.js

https://jira.appcelerator.org/browse/AC-5510
this is a simple project to show the issue https://github.com/darknos/AlloyBrokenSimpleDataBinding

fix simple data binding for models started with upper letter

---

Alloy/commands/compile/index.js
package.json

https://jira.appcelerator.org/browse/ALOY-1595

[ALOY-1595] Use transformFileSync and remove deasync

---

Alloy/lib/alloy/controllers/BaseController.js

Fix for this issue:
[https://jira.appcelerator.org/browse/ALOY-1607](https://jira.appcelerator.org/browse/ALOY-1607)

[ALOY-1607] Fix BaseController.removeListener

---

Alloy/builtins/moment.js

https://jira.appcelerator.org/browse/ALOY-1603

[ALOY-1603] Update Moment.js to version 2.21.0

---

test/projects/HarnessTemplate/tiapp.xml

Remove iphone tag in harness tiapp

---

Alloy/lib/alloy/sync/sql.js

**JIRA**: https://jira.appcelerator.org/browse/ALOY-1617
Although the error is on Android, I think we should fix this in Alloy, since we are using empty column parenthesis `( )` when no columns are specified. iOS may filter this out, but Android complains for a good reason. I did not validate the fix so far, so feedback is welcome!

[ALOY-1617] Attempt to fix SQL error when not using columns in table

---

Alloy/lib/alloy/sync/sql.js

Reverts appcelerator/alloy#895

Revert "[ALOY-1617] Attempt to fix SQL error when not using columns in table"

---

Alloy/lib/alloy/sync/sql.js
package-lock.json
package.json
samples/apps/models/sql_preload/styles/index.tss
samples/apps/models/sql_preload/styles/row.tss

https://jira.appcelerator.org/browse/ALOY-1622
Test steps:
- Copy the code from `samples/apps/models/sql_preload` to an existing Alloy app
- Build for Android

[ALOY-1622] Error on sql migration due to undeclared variable

---

Alloy/builtins/social.js

Everything around it is tabs, so replaced the spaces with tabs. Unsure of how to verify these changes.

Try to fix codeblock in social.js

---

Alloy/commands/compile/parsers/Ti.UI.TextArea.js
Alloy/commands/compile/parsers/Ti.UI.TextField.js
test/apps/testing/ALOY-1304/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1304/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1304/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1304/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1304/controllers/index.js
test/apps/testing/ALOY-1304/styles/index.tss
test/apps/testing/ALOY-1304/views/index.xml

https://jira.appcelerator.org/browse/ALOY-1304

[ALOY-1304] Support Node text for TextField and TextArea

---

Alloy/commands/info/index.js
test/specs/info.js

https://jira.appcelerator.org/browse/ALOY-1630

[ALOY-1630] Remove "localStorage" from info subcommand

---

Alloy/commands/compile/ast/controller.js

https://jira.appcelerator.org/browse/TIMOB-19848

[ALOY-1627] Breakpoints not working on Alloy apps

---

Alloy/commands/compile/index.js
Alloy/commands/compile/parsers/Ti.UI.NavigationWindow.js
Alloy/commands/compile/parsers/Ti.UI.Tab.js
Alloy/commands/compile/parsers/Ti.UI.iOS.SplitWindow.js
Alloy/commands/compile/parsers/Ti.UI.iPhone.NavigationGroup.js
Alloy/common/constants.js

https://jira.appcelerator.org/browse/ALOY-1621

[ALOY-1621] Move NavigationWindow API from Ti.UI.iOS to Ti.UI (parity)

---

Alloy/builtins/animation.js
Alloy/template/lib/alloy.js

https://jira.appcelerator.org/browse/ALOY-1639

[ALOY-1639] Use Matrix2D/Matrix3D instead of 2DMatrix/3DMatrix for sdk 8

---

Alloy/commands/compile/parsers/Alloy.Abstract.BarItemTypes.js
Alloy/commands/compile/parsers/Ti.UI.TabbedBar.js
Alloy/commands/compile/parsers/Ti.UI.iOS.TabbedBar.js
Alloy/common/constants.js

Closes https://jira.appcelerator.org/browse/ALOY-1640
https://github.com/appcelerator/kitchensink-v2/tree/sdk8_changes Can be use to validate this

feat: move TabbedBar to UI namespace

---

Alloy/commands/new/index.js

https://jira.appcelerator.org/browse/ALOY-1632

[ALOY-1632] Allow to import a custom template from dir using Alloy CLI

---

.eslintignore
CHANGELOG.md
Jenkinsfile
dangerfile.js
package-lock.json
package.json
test/lib/ConsoleReporter.js

One part of https://jira.appcelerator.org/browse/ALOY-1642

ci: run tests against ga and master sdk, use pipeline library code

---

Alloy/commands/new/index.js

https://jira.appcelerator.org/browse/ALOY-1652

[ALOY-1652] CLI: Improve handling of missing directories and files in alloy new

---

Alloy/lib/alloy/sync/sql.js
CHANGELOG.md
package-lock.json
package.json

backport and patch release for #930

fix(ios): fix fetch() on iOS due to unbound call to ResultSet.field

---

Alloy/commands/compile/compilerUtils.js
Alloy/common/constants.js
Alloy/lib/alloy/backbone/1.4.0/backbone.js
Alloy/lib/alloy/underscore.js
CHANGELOG.md

underscore: https://jira.appcelerator.org/browse/ALOY-1683
backbone: https://jira.appcelerator.org/browse/ALOY-1648

feat(builtins): update underscore to 1.9.1, add support for backbone 1.4.0

---

Alloy/commands/compile/sourceMapper.js

https://jira.appcelerator.org/browse/ALOY-1698

[ALOY-1698] Compile: Errors thrown during sourcemap step are not visible to a user

---

Alloy/commands/compile/parsers/Ti.UI.WebView.js
CHANGELOG.md
package-lock.json
package.json
test/apps/testing/ALOY-1697/_generated/android/alloy/controllers/index.js
test/apps/testing/ALOY-1697/_generated/ios/alloy/controllers/index.js
test/apps/testing/ALOY-1697/_generated/mobileweb/alloy/controllers/index.js
test/apps/testing/ALOY-1697/_generated/windows/alloy/controllers/index.js
test/apps/testing/ALOY-1697/controllers/index.js
test/apps/testing/ALOY-1697/styles/index.tss
test/apps/testing/ALOY-1697/views/index.xml
tools/create_generated_code.js

JIRA: https://jira.appcelerator.org/browse/ALOY-1697
See ticket for test code

feat(webview): add support for setting onlink in views

---

Alloy/commands/compile/compilerUtils.js
CHANGELOG.md

Fixes [ALOY-1701](https://jira.appcelerator.org/browse/ALOY-1701)

fix(compile): correctly handle platform prefix on event handlers

---

Alloy/commands/compile/sourceMapper.js
CHANGELOG.md

Fix for part of issue in:  https://jira.appcelerator.org/browse/ALOY-1705

fix(compile): allow return outside out function

---

Alloy/lib/alloy/sync/sql.js
CHANGELOG.md

- Cache and maintain database connection to prevent unnecessary `open()` and `close()`
[JIRA Ticket](https://jira.appcelerator.org/browse/ALOY-1693)

impr: maintain db connection

---

Alloy/commands/compile/ast/handle-alloy-globals.js
Alloy/commands/compile/index.js
Alloy/template/app.js
CHANGELOG.md
Jenkinsfile
package.json

https://jira.appcelerator.org/browse/ALOY-1633

fix(runtime): avoid usage of implicit globals

---

Alloy/commands/compile/ast/handle-alloy-globals.js

Ticket: https://jira.appcelerator.org/browse/ALOY-1710

fix(compile): Define 'state' in ImportDeclaration

---

CHANGELOG.md
Jenkinsfile
dangerfile.js
package-lock.json
package.json

ci: setup semantic release

---

Alloy/commands/compile/parsers/Alloy.Abstract.BarItemTypes.js
Alloy/commands/compile/parsers/Ti.UI.OptionBar.js

Closes [ALOY-1746](https://jira.appcelerator.org/browse/ALOY-1746)
See ticket for usage

feat: support using OptionBar

---

Alloy/commands/compile/sourceMapper.js

Fixes ALOY-1749
Test steps in jira

fix(compile): provide filename to babel transform to allow using config files

---

package-lock.json
package.json

Ref: https://snyk.io/blog/open-source-npm-packages-colors-faker/
Long term should move away from colors to chalk

fix: pin colors version to avoid dos issue

---

Alloy/template/gitignore.txt

adding some folders (Android studio, gradle) to the default app gitignore

chore: gitignore items

---

Alloy/commands/compile/compilerUtils.js
Alloy/commands/info/index.js
Alloy/template/lib/alloy.js
samples/lib/testUtils.js
test/specs/compilefile.js
test/specs/new.js

I hate the test timeouts :-) Locally I have
```
Finished in 588.882 seconds
2361 specs, 0 failures
```
let's see if they run online with this configuration.
* increasing timeouts
* removing some left overs for mobile/windows elements

chore: fix tests

---

.github/workflows/build.yml
.github/workflows/publish.yml

This repo is configured for semantic-release so we can let that do the hard work for us

ci(publish): fix command used to publish package

---

Alloy/lib/alloy/underscore.js

Redo of #1336 as the moment en-sg file got included when rebasing, (casing issue on that file?)

feat: update underscore to version 1.13.6
